[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer" },
  { id = "check-toml" },
  { id = "check-yaml" },
]

[[repos]]
repo = "local"
hooks = [
  {
    id = "cargo-fmt",
    name = "cargo fmt",
    language = "system",
    entry = "cargo fmt --all -- --check",
    types = ["rust"],
    pass_filenames = false,
    env = { RUSTFLAGS = "-C linker=clang" },
  },
  {
    id = "cargo-clippy",
    name = "cargo clippy",
    language = "system",
    entry = "cargo clippy --all-targets -- -D warnings",
    types = ["rust"],
    pass_filenames = false,
    env = { RUSTFLAGS = "-C linker=clang" },
  },
]
